# Configuration golangci-lint pour le projet Premier de l'An
# Documentation: https://golangci-lint.run/

run:
  timeout: 5m
  modules-download-mode: readonly
  issues-exit-code: 1

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - gofmt
  disable:
    - ineffassign  # Trop de faux positifs
    - lll
    - misspell    # Projet en français, trop de faux positifs
    - unused      # Fonctions réservées pour usage futur

linters-settings:
  errcheck:
    check-type-assertions: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  staticcheck:
    checks:
      - all
      - "-SA1019"  # Deprecation (bsontype, elliptic)
      - "-SA9003"  # Empty branch
      - "-SA4006"  # Value never used (ineffectual in fcm init)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck  # Certaines erreurs acceptables dans les tests
  max-issues-per-linter: 50
  max-same-issues: 3
