# Configuration golangci-lint pour le projet Premier de l'An
# Documentation: https://golangci-lint.run/

run:
  timeout: 5m
  modules-download-mode: readonly
  issues-exit-code: 1

linters:
  enable:
    - errcheck      # Vérifie les erreurs non gérées
    - gosimple      # Simplifications de code
    - govet         # Analyse statique officielle Go
    - ineffassign   # Assignations inutiles
    - staticcheck   # Analyse statique avancée
    - unused        # Code non utilisé
    - gofmt         # Format du code
    - misspell      # Fautes d'orthographe
  disable:
    - lll           # Longueur de ligne (trop strict)

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
  misspell:
    locale: FR

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck  # Certaines erreurs acceptables dans les tests
  max-issues-per-linter: 50
  max-same-issues: 3
